BaseUrl= "http://example.com/"
LanguageCode= "es"
Title= "Guillermo Caracuel"
paginate = 5
DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "Todos los derechos reservados - 2015"
canonifyurls = true
theme = "hugo-theme-casper"

[params]
  description = "Yet another sysadmin/devops"
  cover = "images/cover.jpg"
  author = "Guillermo Caracuel"
  authorlocation = "Málaga, SPAIN"
  authorwebsite = "http://github.io/gcaracuel"
  bio= ""
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  twitterName = "gcaracuel"
  githubName = "gcaracuel"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Blog"
  weight = 100
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About"
  weight = 101
  identifier = "about"
  url = "about"
